# =========================== Database Configuration ===========================
# Arquivo de configuração da conexão com o banco de dados
# Autor: SilvioLuizSilva
# Versão: 1.0
# ==============================================================================
Database:
  mysql:
    driver: 'jdbc:mysql://'
    host: 'localhost'
    port: '3306'
    name: ''
    user: 'root'
    pass: ''